### ISSUE TITLE
about function tos_list_add_tail

### ISSUE THREAD

**Issue by yang-an-china** [Tencent/TencentOS-tiny#76]
__API__ __STATIC_INLINE__ void tos_list_add_tail(k_list_t *node, k_list_t *list)
{
    _list_add(node, list->prev, list);
}

Should the function meaned tos_list_add_prev?

**Comment by daishengdong** [comment]
logically, if you take the second parameter "list" as a node of one certain list(the first node of the list), the "add tail" logical to a list can be treated as a logic of "add prev" to a certain node(the first node of the list), the code is just equivalent to:
void tos_list_add_prev(k_list_t *node, **k_list_t *first_node_of_the_list**) {
   balabala
}

but semantically, we take the second parameter "list" as a list rather than a node, as a list, "add tail" is a more reasonable function name rather than "add prev"(what's the meaning of add prev to a list?)

as to the "tos_list_add", just consider it as "add head" to a list.

**Comment by yang-an-china** [comment]
ho ho ho，you are wrong, dude.
A ring list designed.

**Comment by daishengdong** [comment]
tos_list.h is an implement of double linked list, aka ring list, each node has a another link to the previous one, more memory space but faster performance to do delete/insert operation, widely used in kernel which cares about the delete/insert performance a lot.

tos_slist.h is an implement of single linked list, each node only has a link to the next one, with less memory space but less good at the "tail add" or delete operation.
